server:
  port: 17777
spring:
  application:
    name: kusch-api-repository
forest:
  # 后端HTTP框架（默认为 okhttp3）
  backend: okhttp3
  # 连接池最大连接数（默认为 500）
  max-connections: 1000
  # 每个路由的最大连接数（默认为 500）
  max-route-connections: 500
  # [自v1.5.22版本起可用] 最大请求等待队列大小
  max-request-queue-size: 100
  # [自v1.5.21版本起可用] 最大异步线程数
  max-async-thread-size: 300
  # [自v1.5.22版本起可用] 最大异步线程池队列大小
  max-async-queue-size: 16
  # [已不推荐使用] 请求超时时间，单位为毫秒（默认为 3000）
  timeout: 30000
  # 连接超时时间，单位为毫秒（默认为 timeout）
  connect-timeout: 30000
  # 数据读取超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 30000
  # 请求失败后重试次数（默认为 0 次不重试）
  max-retry-count: 0
  # 单向验证的HTTPS的默认TLS协议（默认为 TLS）
  ssl-protocol: TLS
  # 打开或关闭日志（默认为 true）
  log-enabled: true
  # 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  # 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true
  # [自v1.5.27版本起可用] 异步模式（默认为 platform）
  async-mode: platform
